site_name: Microsoft365DSC - Your Cloud Configuration
site_url: https://microsoft.github.io/Microsoft365DSC
nav:
  - Home:
      - 'Introduction': 'index.md'
      - 'What is Microsoft365DSC?': 'home/what-is-M365DSC.md'
  - User Guide:
      - 'Get Started': 'user-guide/get-started/complete-story.md'
      - Advanced: 'user-guide/advanced/create-blueprint.md'
      - Cmdlets:
          - 'Assert-M365DSCBlueprint': 'user-guide/cmdlets/Assert-M365DSCBlueprint.md'
          - 'Export-M365DSCConfiguration': 'user-guide/cmdlets/Export-M365DSCConfiguration.md'
          - 'Export-M365DSCDiagnosticData': 'user-guide/cmdlets/Export-M365DSCDiagnosticData.md'
          - 'Get-M365DSCAllResources': 'user-guide/cmdlets/Get-M365DSCAllResources.md'
          - 'Get-M365DSCCompiledPermissionList': 'user-guide/cmdlets/Get-M365DSCCompiledPermissionList.md'
          - 'Get-M365DSCTelemetryOption': 'user-guide/cmdlets/Get-M365DSCTelemetryOption.md'
          - 'Get-M365DSCWorkloadsListFromResourceNames': 'user-guide/cmdlets/Get-M365DSCWorkloadsListFromResourceNames.md'
          - 'Import-M365DSCDependencies': 'user-guide/cmdlets/Import-M365DSCDependencies.md'
          - 'Install-M365DSCDevBranch': 'user-guide/cmdlets/Install-M365DSCDevBranch.md'
          - 'New-M365DSCDeltaReport': 'user-guide/cmdlets/New-M365DSCDeltaReport.md'
          - 'New-M365DSCReportFromConfiguration': 'user-guide/cmdlets/New-M365DSCReportFromConfiguration.md'
          - 'Set-M365DSCAgentCertificateConfiguration': 'user-guide/cmdlets/Set-M365DSCAgentCertificateConfiguration.md'
          - 'Set-M365DSCTelemetryOption': 'user-guide/cmdlets/Set-M365DSCTelemetryOption.md'
          - 'Test-M365DSCAgent': 'user-guide/cmdlets/Test-M365DSCAgent.md'
          - 'Test-M365DSCDependenciesForNewVersions': 'user-guide/cmdlets/Test-M365DSCDependenciesForNewVersions.md'
          - 'Test-M365DSCNewVersionAvailable': 'user-guide/cmdlets/Test-M365DSCNewVersionAvailable.md'
          - 'Update-M365DSCAllowedGraphScopes': 'user-guide/cmdlets/Update-M365DSCAllowedGraphScopes.md'
          - 'Update-M365DSCDependencies': 'user-guide/cmdlets/Update-M365DSCDependencies.md'
          - 'Update-M365DSCResourcesSettingsJSON': 'user-guide/cmdlets/Update-M365DSCResourcesSettingsJSON.md'
  - Contributing:
      - 'Guidelines': 'contributing/contribution-guidelines.md'
      - 'Getting started': 'contributing/getting-started.md'
      - 'Develop a New Resource': 'contributing/develop-new-resource.md'
  - Concepts:
      - 'Breaking Changes Policy': 'concepts/breaking-changes.md'
      - 'OneDrive & SharePoint Permissions': 'concepts/odsp-permissions.md'
      - 'Consent Flow': 'concepts/consent-flow.md'
  - Resources:
      - 'Overview': 'resources/overview.md'
      - 'Azure AD': 'resources/azure-ad'
      - 'Exchange': 'resources/exchange'
      - 'Intune': 'resources/intune'
      - 'Office365': 'resources/office365'
      - 'OneDrive': 'resources/onedrive'
      - 'Planner': 'resources/planner'
      - 'Power Platform': 'resources/power-platform'
      - 'Security & Compliance': 'resources/security-compliance'
      - 'SharePoint': 'resources/sharepoint'
      - 'Teams': 'resources/teams'
  - About:
      - 'Why Microsoft365DSC': 'about/why.md'
      - 'Changelog': https://github.com/microsoft/Microsoft365DSC/blob/master/CHANGELOG.md" target="_blank
      - 'License': 'about/license.md'
      - 'Community Resources': 'about/community-resources.md'
plugins:
  - search
  - include_dir_to_nav
theme:
  name: 'material'
  custom_dir: docs/overrides
  logo: Images/SmallLogo.png
  favicon: Images/favicon.ico
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - search.share
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - attr_list
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/Microsoft365DSC'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/channel/UCveScabVT6pxzqYgGRu17iw'
    - icon: fontawesome/solid/link
      link: 'https://www.powershellgallery.com/packages/Microsoft365DSC/'
  generator: false
  analytics:
    provider: google
    property: UA-209929913-1
repo_url: https://github.com/microsoft/Microsoft365DSC
edit_uri: tree/Dev/docs/docs
copyright: Microsoft365DSC
