name: Unit Tests
on: [push, pull_request]

jobs:
  # This workflow contains a single job called "build"
  UnitTests:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Only when run from the main repo
    if: github.repository == 'microsoft/Microsoft365DSC'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run Test Harness
        shell: powershell
        run: |
          $Dependencies = @(
            @{
                ModuleName      = 'DSCParser'
                RequiredVersion = '1.3.0.6'
            },
            @{
                ModuleName      = 'ExchangeOnlineManagement'
                RequiredVersion = '3.0.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Applications'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Authentication'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.DeviceManagement'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.DeviceManagement.Administration'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.DeviceManagement.Enrolment'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Devices.CorporateManagement'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Groups'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Identity.DirectoryManagement'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Identity.Governance'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Identity.SignIns'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Planner'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Teams'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Users'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.Graph.Users.Actions'
                RequiredVersion = '1.18.0'
            },
            @{
                ModuleName      = 'Microsoft.PowerApps.Administration.PowerShell'
                RequiredVersion = '2.0.154'
            },
            @{
                ModuleName      = 'MicrosoftTeams'
                RequiredVersion = '4.9.1'
            },
            @{
                ModuleName      = "MSCloudLoginAssistant"
                RequiredVersion = "1.0.99"
            },
            @{
                ModuleName      = 'PnP.PowerShell'
                RequiredVersion = '1.12.0'
            },
            @{
                ModuleName      = 'ReverseDSC'
                RequiredVersion = '2.0.0.13'
            }
          )

          foreach ($module in $Dependencies)
          {
            Install-Module $module.ModuleName -Force
            Import-Module $module.ModuleName -Force
          }

          Install-Module Pester -Force -SkipPublisherCheck -RequiredVersion 5.0.4
          [System.Environment]::SetEnvironmentVariable('M365DSCTelemetryEnabled', $false, [System.EnvironmentVariableTarget]::Machine);
          Import-Module './Tests/TestHarness.psm1' -Force;
          $MaximumFunctionCount = 9999

          try
          {
              $results = Invoke-TestHarness -IgnoreCodeCoverage
          }
          catch
          {
              $MaximumFunctionCount = 9999
              Import-Module './Tests/TestHarness.psm1' -Force;
              $results = Invoke-TestHarness -IgnoreCodeCoverage
          }
          if ($results.FailedCount -gt 0)
          {
              throw "{$($results.FailedCount)} Unit Test(s) Failed"
          }
